import type { Metadata } from "next";
import "./globals.css";
import { ThemeScript } from "@/lib/styles/theme-script";
import { Providers } from "./providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR" data-theme="dark">
      <head>
        <ThemeScript />
      </head>
      <body className="bg-[color:var(--color-surface)] text-[color:var(--color-primary)]">
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
